export const Users = [
    {
        image:"Images/ProfilePhotos/images7.jpg",
        name:"Hikayen",
    },
    {
        image:"Images/ProfilePhotos/images2.jpg",
        name:"Yaseminoz",
    },
    {
        image:"Images/ProfilePhotos/images3.jpg",
        name:"eren3141592",
    },
    {
        image:"Images/ProfilePhotos/images4.jpg",
        name:"cercihhasan",
    },
    {
        image:"Images/ProfilePhotos/images5.jpg",
        name:"sosyalistfuhrir",
    },
]